storages:
  database:
    name: posterr
    host: "172.19.0.3"
    port: 27017
post:
  maximum_size: 777
  maximum_page_size: 100
  date_format: "%b %d, %Y"
user:
  name:
    maximum_size: 14
    validate_regex: '\w+' # Only alphanumeric regex
  date_format: "%b %d, %Y"
